# pre-commit hooks for unityflow
# See https://pre-commit.com for more information

# Regex pattern for all Unity YAML file extensions
# Core: prefab, unity (scene), asset
# Animation: anim, controller, overrideController, playable, mask, signal
# Rendering: mat, renderTexture, flare, shadervariants, spriteatlas, cubemap
# Physics: physicMaterial, physicsMaterial2D
# Terrain: terrainlayer, brush
# Audio: mixer
# UI/Editor: guiskin, fontsettings, preset, giparams

- id: prefab-normalize
  name: Normalize Unity YAML files
  description: Normalize Unity YAML files for deterministic serialization
  entry: unityflow normalize --in-place
  language: python
  files: \.(prefab|unity|asset|anim|controller|overrideController|playable|mask|signal|mat|renderTexture|flare|shadervariants|spriteatlas|cubemap|physicMaterial|physicsMaterial2D|terrainlayer|brush|mixer|guiskin|fontsettings|preset|giparams)$
  types: [file]

- id: prefab-normalize-staged
  name: Normalize Unity YAML files (staged only)
  description: Normalize only staged Unity YAML files
  entry: unityflow normalize --changed-only --staged-only
  language: python
  pass_filenames: false
  always_run: true

- id: prefab-validate
  name: Validate Unity YAML files
  description: Validate Unity YAML files for structural correctness
  entry: unityflow validate
  language: python
  files: \.(prefab|unity|asset|anim|controller|overrideController|playable|mask|signal|mat|renderTexture|flare|shadervariants|spriteatlas|cubemap|physicMaterial|physicsMaterial2D|terrainlayer|brush|mixer|guiskin|fontsettings|preset|giparams)$
  types: [file]
